---
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty

    - os: linux
      dist: jessie


before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-get -y install python-pip
 - sudo pip install ansible
 - ansible --version
 - wget --version

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -c local --sudo

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
