---
sudo: required
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=1.9.5
    - env: ANSIBLE_VERSION=2.1.0

before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-get -y install python-pip
 - sudo pip install ansible==$ANSIBLE_VERSION
 - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Provision kibana
  - ansible-playbook tests/test.yml -i tests/inventory -c local --sudo

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
